version: "3.8"

services:
  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    container_name: staff_auth_service
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_PORT=3004
      - USER_AUTO_CLEAN=false
    ports:
      - "3004:3004"
    networks:
      - staff_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3004/health",
        ]
      interval: 2m # Every 2 minutes instead of 30s
      timeout: 10s
      retries: 3

  # Employee Service
  employee-service:
    build:
      context: .
      dockerfile: ./services/employee-service/Dockerfile
    container_name: staff_employee_service
    env_file:
      - .env
    environment:
      - EMPLOYEE_SERVICE_PORT=3002
      - EMPLOYEE_AUTO_CLEAN=false
    ports:
      - "3002:3002"
    networks:
      - staff_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3002/health",
        ]
      interval: 2m # Every 2 minutes instead of 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    container_name: staff_api_gateway
    env_file:
      - .env
    environment:
      - GATEWAY_PORT=8081
      - AUTH_SERVICE_URL=http://auth-service:3004
      - EMPLOYEE_SERVICE_URL=http://employee-service:3002
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - employee-service
    networks:
      - staff_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8081/health",
        ]
      interval: 2m # Every 2 minutes instead of 30s
      timeout: 10s
      retries: 3

networks:
  staff_network:
    driver: bridge
