#!/bin/bash

echo "🔐 Manual Credential Setup for DigitalOcean"
echo "==========================================="

echo "1. Your services are now on DigitalOcean: https://cloud.digitalocean.com/apps"
echo "2. To check current environment variables, go to your app settings"
echo "3. Note: Migration is complete, this script is for reference only"
echo ""
echo "📋 FROM AUTH SERVICE:"
echo "   - USER_DB_URL"
echo "   - PASETO_SECRET_KEY" 
echo "   - SMTP_USERNAME"
echo "   - SMTP_PASSWORD"
echo ""
echo "📋 FROM EMPLOYEE SERVICE:"
echo "   - EMPLOYEE_DB_URL"
echo ""
echo "📋 FROM YOUR SETUP:"
echo "   - GitHub username"
echo "   - GitHub repository name"
echo "   - Frontend URL (Vercel/Netlify)"
echo ""
echo "4. Then edit .do/app.yaml and replace:"
echo "   - YOUR_GITHUB_USERNAME → your username"
echo "   - YOUR_REPO_NAME → your repo"
echo "   - YOUR_NEON_DATABASE_URL → your DB URL"
echo "   - YOUR_PASETO_SECRET → your secret"
echo "   - YOUR_SMTP_USERNAME → your SMTP user"
echo "   - YOUR_SMTP_PASSWORD → your SMTP pass"
echo "   - https://yourapp.vercel.app → your frontend URL"
echo ""
echo "5. Save and run: doctl apps create .do/app.yaml" 