name: staff-scheduler
services:
  # API Gateway Service (Public)
  - name: api-gateway
    source_dir: /
    github:
      repo: harrishphotos/staff-scheduler
      branch: main
    dockerfile_path: services/api-gateway/Dockerfile
    http_port: 8081
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /health
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 2
    envs:
      - key: GATEWAY_PORT
        value: "8081"
      - key: AUTH_SERVICE_URL
        value: "${auth-service.PRIVATE_URL}"
      - key: EMPLOYEE_SERVICE_URL
        value: "${employee-service.PRIVATE_URL}"
      - key: ALLOWED_ORIGINS
        value: "https://staffscheduler.software,http://localhost:5173,http://localhost:3001"
      - key: ENVIRONMENT
        value: "production"
    routes:
      - path: /

  # Auth Service (Internal)
  - name: auth-service
    source_dir: /
    github:
      repo: harrishphotos/staff-scheduler
      branch: main
    dockerfile_path: services/auth-service/Dockerfile
    internal_ports:
      - 3004
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /health
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 2
    envs:
      - key: AUTH_SERVICE_PORT
        value: "3004"
      - key: USER_DB_URL
        value: "YOUR_NEON_DATABASE_URL"
        type: SECRET
      - key: USER_AUTO_CLEAN
        value: "false"
      - key: PASETO_SECRET_KEY
        value: "YOUR_PASETO_SECRET"
        type: SECRET
      - key: ACCESS_TOKEN_EXPIRATION
        value: "15m"
      - key: SMTP_HOST
        value: "smtp-relay.brevo.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: "YOUR_SMTP_USERNAME"
        type: SECRET
      - key: SMTP_PASSWORD
        value: "YOUR_SMTP_PASSWORD"
        type: SECRET
      - key: SMTP_FROM
        value: "it23291782@my.sliit.lk"
      - key: APP_URL
        value: "${api-gateway.PUBLIC_URL}"
      - key: FRONTEND_URL
        value: "https://staffscheduler.software"
      - key: ENVIRONMENT
        value: "production"

  # Employee Service (Internal)
  - name: employee-service
    source_dir: /
    github:
      repo: harrishphotos/staff-scheduler
      branch: main
    dockerfile_path: services/employee-service/Dockerfile
    internal_ports:
      - 3002
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /health
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 2
    envs:
      - key: EMPLOYEE_SERVICE_PORT
        value: "3002"
      - key: EMPLOYEE_DB_URL
        value: "YOUR_NEON_DATABASE_URL"
        type: SECRET
      - key: EMPLOYEE_AUTO_CLEAN
        value: "false"
      - key: ENVIRONMENT
        value: "production"
